on:
  schedule:
    - cron:  '0 4 ? * SUN'
  workflow_dispatch:
jobs:
  multi-registries:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch
        id: getbranch
        run: echo "THIS_BRANCH=$(basename -s .yml {{ github.workflow }})" >> $GITHUB_ENV
      
      - name: Get current date
        id: date
        run: echo "TODAY=$(date +'%Y%m%d')" >> $GITHUB_ENV
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ env.THIS_BRANCH }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PACKAGE_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            greyltc/${{ env.THIS_BRANCH }}:latest
            greyltc/${{ env.THIS_BRANCH }}:${{ env.TODAY }}.0.${{ github.run_number }}
            ghcr.io/greyltc/${{ env.THIS_BRANCH }}:latest
            ghcr.io/greyltc/${{ env.THIS_BRANCH }}:${{ env.TODAY }}.0.${{ github.run_number }}
